# Generated by Django 3.1.6 on 2021-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210429_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Berlin', max_length=50),
            preserve_default=False,
        ),
    ]
