# Generated by Django 3.1.6 on 2021-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
