# Generated by Django 3.1.6 on 2021-04-08 12:38

from django.db import migrations


def add_pcb_category(apps, schema_editor):
    ArticleCategory = apps.get_model('article', 'ArticleCategory')
    pcb_cat = ArticleCategory(
        articleCategoryID=1,
        name="PCB",
        description="Printed Circuit Board"
    )
    pcb_cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210317_1710'),
    ]

    operations = [
        migrations.RunPython(add_pcb_category)
    ]
