# Generated by Django 3.1.6 on 2021-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210408_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='board',
            name='castellatedHoles',
        ),
        migrations.RemoveField(
            model_name='board',
            name='color',
        ),
        migrations.RemoveField(
            model_name='board',
            name='confirmProdFile',
        ),
        migrations.RemoveField(
            model_name='board',
            name='copperWeight',
        ),
        migrations.RemoveField(
            model_name='board',
            name='deliveryFormat',
        ),
        migrations.RemoveField(
            model_name='board',
            name='differentDesigns',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dimensionX',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dimensionY',
        ),
        migrations.RemoveField(
            model_name='board',
            name='flyingProbeTest',
        ),
        migrations.RemoveField(
            model_name='board',
            name='goldFingers',
        ),
        migrations.RemoveField(
            model_name='board',
            name='layers',
        ),
        migrations.RemoveField(
            model_name='board',
            name='removeOrderNum',
        ),
        migrations.RemoveField(
            model_name='board',
            name='surfaceFinish',
        ),
        migrations.RemoveField(
            model_name='board',
            name='thickness',
        ),
        migrations.AddField(
            model_name='board',
            name='attributes',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
