# Generated by Django 3.1.6 on 2021-04-17 09:28


from django.db import migrations


def add_external_shop(apps, schema_editor):
    ExternalShop = apps.get_model('article', 'ExternalShop')
    example_shop = ExternalShop(
        name="Example PCB Shop",
        country="Germany"
    )
    example_shop.save()


def add_external_shop_options(apps, schema_editor):
    ExternalBoardOptions = apps.get_model('article', 'ExternalBoardOptions')
    ExternalShop = apps.get_model('article', 'ExternalShop')
    shop = ExternalShop.objects.get(name="Example PCB Shop")

    EXAMPLE_ATTRIBUTE_OPTIONS = {
        "dimensionX": {
            "range": {
                "min": 6,
                "max": 400,

            }
        },
        "num_designs": {
            "choices": [1, 2],
        },
        "quantity": {
            "choices": [1, 2, 3, 4, 5, 10, 20, 50, 100]
        }
    }

    example_options = ExternalBoardOptions(
        external_shop=shop,
        attribute_options=EXAMPLE_ATTRIBUTE_OPTIONS
    )
    example_options.save()


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210417_1125'),
    ]

    operations = [
        migrations.RunPython(add_external_shop),
        migrations.RunPython(add_external_shop_options)
    ]
