# Generated by Django 3.1.6 on 2021-04-17 12:21

from django.db import migrations


def add_jlcpcb_shop(apps, schema_editor):
    ExternalShop = apps.get_model('article', 'ExternalShop')
    jlcpcb = ExternalShop(
        name="JLCPCB",
        country="China"
    )
    jlcpcb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210417_1128'),
    ]

    operations = [
        migrations.RunPython(add_jlcpcb_shop)
    ]
