# Generated by Django 3.1.6 on 2021-04-19 10:04

import article.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210417_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredboardoptions',
            name='attribute_options',
            field=models.JSONField(validators=[article.validators.BoardOptionValidator.validate]),
        ),
    ]
