# Generated by Django 3.1.6 on 2021-04-19 10:17

import article.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210419_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredboardoptions',
            name='attribute_options',
            field=models.JSONField(validators=[article.validators.BoardOptionValidator]),
        ),
    ]
