# Generated by Django 3.1.6 on 2021-04-19 10:39

import src.article.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210419_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredboardoptions',
            name='attribute_options',
            field=models.JSONField(validators=[src.article.validators.validate_external_consistency]),
        ),
    ]
