# Generated by Django 3.1.6 on 2021-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_billing_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_shipping_address',
        ),
        migrations.AddField(
            model_name='address',
            name='is_billing_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_shipping_default',
            field=models.BooleanField(default=False),
        ),
    ]
