# Generated by Django 3.1.6 on 2021-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210419_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterModelOptions(
            name='externalboardoptions',
            options={'ordering': ['-created'], 'verbose_name': 'External Board Options', 'verbose_name_plural': 'External Board Options List'},
        ),
        migrations.AlterModelOptions(
            name='externalshop',
            options={'verbose_name': 'Eternal Shop'},
        ),
        migrations.AlterModelOptions(
            name='offeredboardoptions',
            options={'ordering': ['-created'], 'verbose_name': 'Offered Board Options', 'verbose_name_plural': 'Offered Board Options List'},
        ),
    ]
