# Generated by Django 3.1.6 on 2021-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20210419_1327'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externalboardoptions',
            index=models.Index(fields=['-created'], name='article_ext_created_965d89_idx'),
        ),
        migrations.AddIndex(
            model_name='offeredboardoptions',
            index=models.Index(fields=['-created'], name='article_off_created_0a8a1a_idx'),
        ),
    ]
