# Generated by Django 3.1.6 on 2021-04-23 09:24

from django.db import migrations


def add_shipping_method(apps, schema_editor):
    ShippingMethod = apps.get_model('order', 'ShippingMethod')
    example_shipping_method = ShippingMethod(
        name="Example Shipping Method",
        price=2.99,
        sorter=1
    )
    example_shipping_method.save()


def add_order_states(apps, schema_editor):
    OrderState = apps.get_model('order', 'OrderState')
    order_state = OrderState(
        name="received",
        description="Order was received, but has not been confirmed yet."
    )
    order_state.save()

    order_state = OrderState(
        name="confirmed",
        description="Order has been externally validated and confirmed."
    )
    order_state.save()


def add_payment_states(apps, schema_editor):
    PaymentState = apps.get_model('order', 'PaymentState')
    payment_state = PaymentState(
        name="pending",
        description="No payment has been issued yet."
    )
    payment_state.save()

    payment_state = PaymentState(
        name="incomplete",
        description="A payment has been received, but it is incomplete."
    )
    payment_state.save()

    payment_state = PaymentState(
        name="complete",
        description="A complete payment has been received."
    )
    payment_state.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_shipping_method),
        migrations.RunPython(add_order_states),
        migrations.RunPython(add_payment_states)
    ]
