# Generated by Django 3.1.6 on 2021-04-26 09:51

from django.db import migrations


def add_shipping_provider(apps, schema_editor):
    ShippingProvider = apps.get_model('order', 'ShippingProvider')
    shipping_provider = ShippingProvider(
        name="Example Shipping Provider",
        country="Germany"
    )
    shipping_provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210426_1151'),
    ]

    operations = [
        migrations.RunPython(add_shipping_provider)
    ]
