# Generated by Django 3.1.6 on 2021-03-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='defaultBillingAddress',
            new_name='default_billing_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='defaultShippingAddress',
            new_name='default_shipping_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
