# Generated by Django 3.1.6 on 2021-04-03 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210401_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
