# Generated by Django 3.1.6 on 2021-04-20 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0012_auto_20210419_1327'),
        ('user', '0007_auto_20210403_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('owner', 'article')},
        ),
    ]
